name: Automatic Wii Compiler

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make the DOL
        run: |
          export PATH=$DEVKITPPC/bin:$DEVKITPRO/tools/bin:$PATH
          
          powerpc-eabi-gcc -g -O2 -Wall -mrvl -mcpu=750 -meabi -mhard-float -DGECKO -DHW_RVL \
            -I$DEVKITPRO/libogc/include \
            main.c \
            -L$DEVKITPRO/libogc/lib/wii -Wl,--start-group -lfat -lwiiuse -lbte -logc -lm -Wl,--end-group \
            -o boot.elf
          
          elf2dol boot.elf boot.dol

      - name: Prepare Release Folder
        run: |
          mkdir -p "release/apps/Wii Save"
          cp boot.dol "release/apps/Wii Save/"
          cp "apps/Wii Save/meta.xml" "release/apps/Wii Save/"
          
          if [ -f "apps/Wii Save/icon.png" ]; then
            cp "apps/Wii Save/icon.png" "release/apps/Wii Save/"
          fi
          
          if [ -d "apps/d2x-cios-installer" ]; then
            cp -r apps/d2x-cios-installer release/apps/
          fi

      - name: Save the ready Release Package
        uses: actions/upload-artifact@v4
        with:
          name: Wii_Save_Extractor_With_cIOS_Installer
          path: release/
