name: Automatic Wii Compiler

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make the DOL
        run: |
          export PATH=$DEVKITPPC/bin:$DEVKITPRO/tools/bin:$PATH
          
          powerpc-eabi-gcc -g -O2 -Wall -mrvl -mcpu=750 -meabi -mhard-float -DGECKO -DHW_RVL \
            -I$DEVKITPRO/libogc/include \
            main.c \
            -L$DEVKITPRO/libogc/lib/wii -lfat -lwiiuse -logc -lm \
            -o boot.elf
          
          elf2dol boot.elf boot.dol

      - name: Prepare Release Folder
        run: |
          mkdir -p release/apps/WiiSave
          cp boot.dol release/apps/WiiSave/
          cp apps/WiiSave/meta.xml release/apps/WiiSave/
          
          if [ -f "apps/WiiSave/icon.png" ]; then
            cp apps/WiiSave/icon.png release/apps/WiiSave/
          fi
          
          if [ -d "apps/d2x-cios-installer" ]; then
            cp -r apps/d2x-cios-installer release/apps/
          fi

      - name: Save the ready Release Package
        uses: actions/upload-artifact@v4
        with:
          name: Wii_Save_Extractor_With_cIOS_Installer
          path: release/
